services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    container_name: filebox-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - snuggle-net

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: filebox-backend
    restart: unless-stopped
    environment:
      POSTGRES_URL: postgresql://mycutieuser:supersecretnyaa123@db:5432/fileboxdb
    ports:
      - "3456:3456"
    depends_on:
      - db
    networks:
      - snuggle-net

  db:
    image: postgres:17
    container_name: filebox-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mycutieuser
      POSTGRES_PASSWORD: supersecretnyaa123
      POSTGRES_DB: fileboxdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - snuggle-net

volumes:
  pgdata:

networks:
  snuggle-net:
